### ISSUE TITLE
NSFW failed to load

### ISSUE THREAD

**Issue by unlightednetting** [Meisterlala/NekoLife#7] opened 2022-11-20 21:59 UTC
Hi, when I paste the code into experimental, as shown in the video, nothing happens.

When I download manually, the icon works. But, "This plugin failed to load. Please contact the author for more information"

1.2.0 of main, and 1.0.1 of nsfw I believe, from the latest download link.

Dalamud D7.3.0.0(9e0bb16
FFXIVCS 9cb2eb3

**Comment by Meisterlala** [comment] 2022-11-21 02:05
The "This plugin failed to load. Please contact the author for more information" error occurs when the plugin is already loaded and you try to load it again.

I just tried adding the custom plugin repository URL myself and I can't reproduce your error while having the same version of Dalamud and Neko Fans installed. 

Please make sure that your Dalamud settings look like this:
![how it should look](https://user-images.githubusercontent.com/6453306/202944145-884f9ed0-8336-4fa9-8447-399994b3c41b.png)
A common mistake is to not press the "+" button after entering the URL in the text field. After this you should be able to find the NSFW 18+ patch in the list of all plugins in the UI category.

If this doesn't fix your problem, then please post your log files here. You can find them at `%AppData%\XIVLauncher\dalamud.log` or `C:\Users\[your username]\XIVLauncher\dalamud.log` or by typing `\xllog` in game

**Comment by unlightednetting** [comment] 2022-11-21 03:54
[dalamud.log](https://github.com/Meisterlala/NekoFans/files/10053246/dalamud.log)

Thank you. I did manage to figure out how to get the check mark, and restarted a few times. I found an error, but my experience in coding does tell me that it could very easily be where I saved it, etc.

**Comment by Meisterlala** [comment] 2022-11-21 15:45
I can see from the logs, that you added the URL correctly. You should now be able to install the 18+ Patch from the list of all plugins. If you want to use the files you downloaded manually, then the plugin will be in the "Dev Tools" section of the plugin installer. 
![image](https://user-images.githubusercontent.com/6453306/203095909-b77a8e4e-861e-435c-a90b-532eac201df1.png)
Once it is enabled you can open the Neko Fans configuration menu by typing `/nekocfg` and some of the image sources now have more configuration option available. For example "WAIFU.IM" should now have a content option "NSFW Images"

**Comment by unlightednetting** [comment] 2022-11-21 19:48
You are right, thank you.... I think I was looking in Installed Plugins, instead of  UI.... Even using the search menu up top, but only in Installed Plugins. I have found it now.

Does the log tell why the manual file download did not work? That was where I found the error, I am curious about these kinds of things

**Closed as completed** 2022-11-22 15:39 UTC
